#!/bin/bash
# Script to setup .env file with HOST_PROJECT_ROOT automatically detected

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Nayarta On-Premise Compose - Env Setup${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Get the directory where the script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

echo -e "${YELLOW}Detected project root: ${PROJECT_ROOT}${NC}"
echo ""

# Check if .env already exists
if [ -f "$PROJECT_ROOT/.env" ]; then
    echo -e "${YELLOW}.env file already exists!${NC}"
    read -p "Do you want to update HOST_PROJECT_ROOT only? (y/n): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        # Update HOST_PROJECT_ROOT in existing .env
        if grep -q "^HOST_PROJECT_ROOT=" "$PROJECT_ROOT/.env"; then
            # Update existing HOST_PROJECT_ROOT
            if [[ "$OSTYPE" == "darwin"* ]]; then
                # macOS
                sed -i '' "s|^HOST_PROJECT_ROOT=.*|HOST_PROJECT_ROOT=$PROJECT_ROOT|" "$PROJECT_ROOT/.env"
            else
                # Linux
                sed -i "s|^HOST_PROJECT_ROOT=.*|HOST_PROJECT_ROOT=$PROJECT_ROOT|" "$PROJECT_ROOT/.env"
            fi
            echo -e "${GREEN}✓ Updated HOST_PROJECT_ROOT in .env${NC}"
        else
            # Add HOST_PROJECT_ROOT if not exists
            echo "" >> "$PROJECT_ROOT/.env"
            echo "# Project root path (auto-detected)" >> "$PROJECT_ROOT/.env"
            echo "HOST_PROJECT_ROOT=$PROJECT_ROOT" >> "$PROJECT_ROOT/.env"
            echo -e "${GREEN}✓ Added HOST_PROJECT_ROOT to .env${NC}"
        fi
        echo ""
        echo -e "${GREEN}Setup complete!${NC}"
        echo -e "${YELLOW}HOST_PROJECT_ROOT is set to: ${PROJECT_ROOT}${NC}"
        exit 0
    else
        echo -e "${RED}Cancelled.${NC}"
        exit 1
    fi
fi

# Create .env from .env.example if it exists
if [ -f "$PROJECT_ROOT/.env.example" ]; then
    echo -e "${YELLOW}Creating .env from .env.example...${NC}"
    cp "$PROJECT_ROOT/.env.example" "$PROJECT_ROOT/.env"
    
    # Update HOST_PROJECT_ROOT
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS
        sed -i '' "s|^HOST_PROJECT_ROOT=.*|HOST_PROJECT_ROOT=$PROJECT_ROOT|" "$PROJECT_ROOT/.env"
    else
        # Linux
        sed -i "s|^HOST_PROJECT_ROOT=.*|HOST_PROJECT_ROOT=$PROJECT_ROOT|" "$PROJECT_ROOT/.env"
    fi
    
    echo -e "${GREEN}✓ Created .env file${NC}"
    echo -e "${GREEN}✓ Set HOST_PROJECT_ROOT to: ${PROJECT_ROOT}${NC}"
    echo ""
    echo -e "${YELLOW}⚠️  IMPORTANT: Please review and update other values in .env file!${NC}"
    echo -e "${YELLOW}   Especially: DB_PASSWORD, MINIO_ROOT_PASSWORD, etc.${NC}"
else
    # Create minimal .env file
    echo -e "${YELLOW}Creating minimal .env file...${NC}"
    cat > "$PROJECT_ROOT/.env" << EOF
# Nayarta On-Premise Compose Environment Variables
# Generated by setup-env.sh

# Project root path (auto-detected)
HOST_PROJECT_ROOT=$PROJECT_ROOT

# Host IP (update as needed)
HOST_IP=localhost

# Database Configuration
DB_NAME=vms_development
DB_USER=admin
DB_PASSWORD=your_secure_password_here

# Add other environment variables as needed
EOF
    echo -e "${GREEN}✓ Created minimal .env file${NC}"
    echo -e "${YELLOW}⚠️  Please copy from .env.example and update values!${NC}"
fi

echo ""
echo -e "${GREEN}Setup complete!${NC}"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo -e "1. Review and update .env file with your configuration"
echo -e "2. Run: docker compose --profile appstack up -d"
